export interface VscodeExtension {
  id: string
  note?: string
  noteZh?: string
}

export const vscodeExtensions: VscodeExtension[] = [
  { id: 'acidic9.p5js-snippets' },
  { id: 'amandeepmittal.pug' },
  { id: 'anseki.vscode-color' },
  { id: 'antfu.browse-lite' },
  { id: 'antfu.goto-alias' },
  { id: 'antfu.iconify' },
  { id: 'antfu.slidev' },
  { id: 'antfu.unocss' },
  { id: 'antfu.vite' },
  { id: 'bierner.color-info' },
  { id: 'bierner.lit-html' },
  { id: 'bradlc.vscode-tailwindcss' },
  { id: 'bungcip.better-toml' },
  { id: 'cesium.gltf-vscode' },
  { id: 'christian-kohler.path-intellisense' },
  { id: 'csstools.postcss' },
  { id: 'DavidAnson.vscode-markdownlint' },
  { id: 'dbaeumer.vscode-eslint' },
  { id: 'donjayamanne.githistory' },
  { id: 'dsznajder.es7-react-js-snippets' },
  { id: 'ducfilan.pug-formatter' },
  { id: 'eamodio.gitlens' },
  { id: 'ecmel.vscode-html-css' },
  { id: 'EditorConfig.EditorConfig' },
  { id: 'esbenp.prettier-vscode' },
  { id: 'formulahendry.auto-rename-tag' },
  { id: 'formulahendry.code-runner' },
  { id: 'foxundermoon.shell-format' },
  { id: 'fumobox.vtool' },
  { id: 'gera2ld.markmap-vscode' },
  { id: 'GitHub.codespaces' },
  { id: 'GitHub.copilot' },
  { id: 'GitHub.vscode-pull-request-github' },
  { id: 'goessner.mdmath' },
  { id: 'golang.go' },
  { id: 'GrapeCity.gc-excelviewer' },
  { id: 'Gruntfuggly.todo-tree' },
  { id: 'hediet.vscode-drawio' },
  { id: 'James-Yu.latex-workshop' },
  { id: 'jock.svg' },
  { id: 'josetr.cmake-language-support-vscode' },
  { id: 'julianchen.babylon-js-viewer' },
  { id: 'lokalise.i18n-ally' },
  { id: 'mechatroner.rainbow-csv' },
  { id: 'meowtec.schema-language' },
  { id: 'mikestead.dotenv' },
  { id: 'mongodb.mongodb-vscode' },
  { id: 'mrmlnc.vscode-apache' },
  { id: 'ms-azuretools.vscode-docker' },
  { id: 'ms-dotnettools.csharp' },
  { id: 'ms-dotnettools.vscode-dotnet-runtime' },
  { id: 'ms-python.isort' },
  { id: 'ms-python.python' },
  { id: 'ms-python.vscode-pylance' },
  { id: 'ms-toolsai.jupyter' },
  { id: 'ms-toolsai.jupyter-keymap' },
  { id: 'ms-toolsai.jupyter-renderers' },
  { id: 'ms-toolsai.vscode-jupyter-cell-tags' },
  { id: 'ms-toolsai.vscode-jupyter-slideshow' },
  { id: 'ms-vscode-remote.remote-ssh' },
  { id: 'ms-vscode-remote.remote-ssh-edit' },
  { id: 'ms-vscode-remote.remote-wsl' },
  { id: 'ms-vscode.cmake-tools' },
  { id: 'ms-vscode.cpptools' },
  { id: 'ms-vscode.hexeditor' },
  { id: 'ms-vscode.remote-explorer' },
  { id: 'ms-vsliveshare.vsliveshare' },
  { id: 'octref.vetur' },
  {
    id: 'phr0s.bib',
    note: 'BibTeX syntax highlighting; useful when writing papers.',
    noteZh: 'BibTeX 语法高亮，写论文时使用。',
  },
  { id: 'piersdeseilligny.betterfountain' },
  { id: 'PKief.material-icon-theme' },
  { id: 'pnp.polacode' },
  { id: 'qiu8310.minapp-vscode' },
  { id: 'redhat.vscode-commons' },
  { id: 'redhat.vscode-xml' },
  { id: 'redhat.vscode-yaml' },
  { id: 'ritwickdey.LiveServer' },
  { id: 'rust-lang.rust-analyzer' },
  { id: 'saekiraku.rainbow-fart' },
  { id: 'slevesque.shader' },
  { id: 'slevesque.vscode-3dviewer' },
  { id: 'streetsidesoftware.code-spell-checker' },
  { id: 'stylelint.vscode-stylelint' },
  { id: 'syler.sass-indented' },
  { id: 'sysoev.language-stylus' },
  { id: 'takayama.vscode-qq' },
  { id: 'thisismanta.stylus-supremacy' },
  { id: 'tombonnike.vscode-status-bar-format-toggle' },
  { id: 'twxs.cmake' },
  { id: 'uctakeoff.vscode-counter' },
  { id: 'usernamehw.errorlens' },
  { id: 'voorjaar.windicss-intellisense' },
  { id: 'Vue.volar' },
  { id: 'Vue.vscode-typescript-vue-plugin' },
  { id: 'weixin-cloudbase.vscode-docker-wx-cloudbase' },
  { id: 'Yaji.cocos-effect' },
  { id: 'yzhang.markdown-all-in-one' },
  { id: 'zhuangtongfa.material-theme' },
]
