"$schema" = "https://starship.rs/config-schema.json"
add_newline = true
command_timeout = 1000
format = """
[░▒▓](#a3aed2)\
$os\
[](bg:#7aa2f7 fg:#a3aed2)\
$directory\
[](fg:#7aa2f7 bg:#394260)\
$git_branch\
$git_state\
$git_status\
$git_metrics\
[](fg:#394260 bg:#212736)\
$nodejs\
$bun\
$deno\
$rust\
$golang\
$php\
$package\
[ ](bg:#212736)\
[](fg:#212736 bg:#1d2230)\
$cmd_duration\
$time\
$status\
[ ](bg:#1d2230)\
[ ](fg:#1d2230)\
\n$character"""

[character]
success_symbol = "[❯](bold #9ece6a)"
error_symbol = "[❯](bold #f7768e)"
vimcmd_symbol = "[❮](bold #7aa2f7)"

[os]
disabled = false
format = "[ $symbol ]($style)"
style = "bg:#a3aed2 fg:#090c0c"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
CentOS = ""
Debian = "󰣚"
Fedora = "󰣛"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
Pop = ""
Raspbian = "󰐿"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"

[directory]
format = "[ $path ]($style)"
style = "fg:#1a1b26 bg:#7aa2f7"
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = false

[directory.substitutions]
Documents = "󰈙 "
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
format = "[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)"
style = "bg:#394260"
symbol = ""

[git_state]
format = "[[$state( $progress_current/$progress_total) ](fg:#e0af68 bg:#394260)]($style)"
style = "bg:#394260"

[git_status]
format = "[[$all_status$ahead_behind](fg:#e0af68 bg:#394260)]($style)"
style = "bg:#394260"
conflicted = "[=$count](fg:#f7768e bg:#394260) "
deleted = "[-$count](fg:#f7768e bg:#394260) "
renamed = "[>$count](fg:#7dcfff bg:#394260) "
modified = "[~$count](fg:#e0af68 bg:#394260) "
staged = "[+$count](fg:#9ece6a bg:#394260) "
stashed = "[stash $count](fg:#bb9af7 bg:#394260) "
typechanged = "[T$count](fg:#e0af68 bg:#394260) "
untracked = "[?$count](fg:#7aa2f7 bg:#394260) "
ahead = "[ $count](fg:#9ece6a bg:#394260) "
behind = "[ $count](fg:#f7768e bg:#394260) "
diverged = "[  $ahead_count  $behind_count](fg:#bb9af7 bg:#394260) "

[git_metrics]
disabled = false
format = "([](fg:#7aa2f7 bg:#394260)([ +$added]($added_style))([ -$deleted]($deleted_style))[ ](bg:#394260))"
only_nonzero_diffs = true
added_style = "fg:#9ece6a bg:#394260"
deleted_style = "fg:#f7768e bg:#394260"

[nodejs]
format = "[[ $symbol $version](fg:#769ff0 bg:#212736)]($style)"
style = "bg:#212736"
symbol = ""

[bun]
format = "[[ $symbol $version](fg:#769ff0 bg:#212736)]($style)"
style = "bg:#212736"
symbol = ""

[deno]
format = "[[ $symbol $version](fg:#769ff0 bg:#212736)]($style)"
style = "bg:#212736"
symbol = ""

[rust]
format = "[[ $symbol $version](fg:#769ff0 bg:#212736)]($style)"
style = "bg:#212736"
symbol = ""

[golang]
format = "[[ $symbol $version](fg:#769ff0 bg:#212736)]($style)"
style = "bg:#212736"
symbol = ""

[php]
format = "[[ $symbol $version](fg:#769ff0 bg:#212736)]($style)"
style = "bg:#212736"
symbol = ""

[package]
format = "[[ $symbol $version](fg:#7aa2f7 bg:#212736)]($style)"
style = "bg:#212736"
symbol = "󰏗"
display_private = true

[cmd_duration]
min_time = 1000
format = "[[ took $duration](fg:#e0af68 bg:#1d2230)]($style)"
style = "bg:#1d2230"

[time]
disabled = false
format = "[[  $time](fg:#a0a9cb bg:#1d2230)]($style)"
style = "bg:#1d2230"
time_format = "%R"

[status]
disabled = false
format = "[[ exit $status](fg:#f7768e bg:#1d2230)]($style)"
style = "bg:#1d2230"
